"""Lightweight local image generator using Stable Diffusion via Hugging Face diffusers.

Optimized defaults favour low VRAM usage (~4 GB) by selecting ``stabilityai/sdxl-turbo`` which can
produce a passable 512x512 image in 1‒4 steps. There is also an ``--engine kandinsky2.2`` mode
leveraging ``kandinsky-community/kandinsky-2-2-decoder`` for even smaller footprint at the cost of
detail.

Run on Windows PowerShell:
    python tools\local_image_generator.py --prompt "colorful thai lottery booth" --output generated\out.png

The script auto-detects CUDA/MPS; otherwise it runs on CPU. CPU generation stays slow but the
low-step pipelines keep it manageable. Use ``--model`` to override with a different Stable Diffusion
checkpoint if you have adequate VRAM.
"""
from __future__ import annotations

import argparse
import os
import re
from pathlib import Path
from typing import Optional

try:
    import torch  # type: ignore
    from diffusers import (  # type: ignore
        AutoencoderKL,
        DPMSolverMultistepScheduler,
        KandinskyV22PriorPipeline,
        KandinskyV22Pipeline,
        StableDiffusionPipeline,
    )
except ImportError as exc:  # pragma: no cover - environment guard
    raise SystemExit(
        "Missing Python packages. Install dependencies first:\n"
        "  pip install -r tools/requirements_local_ai.txt"
    ) from exc


def positive_int(value: str) -> int:
    parsed = int(value)
    if parsed <= 0:
        raise argparse.ArgumentTypeError("value must be positive")
    return parsed


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate an image locally from a text prompt.")
    parser.add_argument(
        "--prompt",
        default=None,
        help="custom main text prompt; if omitted and --numbers provided, an automatic Thai lottery prompt is generated",
    )
    parser.add_argument(
        "--negative",
        default="",
        help="optional negative prompt to push the model away from unwanted details",
    )
    parser.add_argument(
        "--output",
        default="generated/output.png",
        help="path to save the generated PNG (folders will be created automatically)",
    )
    parser.add_argument(
        "--numbers",
        nargs="*",
        default=None,
        help="list of numbers (e.g. 500 23 789) to convert into Thai readings and embed into the prompt",
    )
    parser.add_argument(
        "--bg-name",
        default="bg_custom_เซียนตอง",
        help="background asset name to reference inside the autogenerated prompt",
    )
    parser.add_argument(
        "--engine",
        default="sdxl-turbo",
        choices=["sdxl-turbo", "sd15", "kandinsky2.2"],
        help="preset choice balancing quality vs speed (default sdxl-turbo ~1 step)",
    )
    parser.add_argument(
        "--model",
        default=None,
        help="optional custom model id/path overriding the selected engine",
    )
    parser.add_argument(
        "--steps",
        type=positive_int,
        default=4,
        help="number of inference steps (more steps = slower but higher quality)",
    )
    parser.add_argument(
        "--guidance",
        type=float,
        default=None,
        help="guidance scale (engine-specific default if omitted)",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=None,
        help="random seed for reproducibility; omit to auto-generate",
    )
    parser.add_argument(
        "--height",
        type=positive_int,
    default=512,
        help="output image height (pixels)",
    )
    parser.add_argument(
        "--width",
        type=positive_int,
    default=512,
        help="output image width (pixels)",
    )
    parser.add_argument(
        "--local-files",
        action="store_true",
        help="only use local model weights; fail if download is required",
    )
    return parser


def resolve_device() -> tuple[str, torch.dtype]:
    if torch.cuda.is_available():
        return "cuda", torch.float16
    if torch.backends.mps.is_available():
        return "mps", torch.float16
    return "cpu", torch.float32


THAI_DIGITS = {
    "0": "ศูนย์",
    "1": "หนึ่ง",
    "2": "สอง",
    "3": "สาม",
    "4": "สี่",
    "5": "ห้า",
    "6": "หก",
    "7": "เจ็ด",
    "8": "แปด",
    "9": "เก้า",
}


def digits_to_thai_words(number: str) -> str:
    return " ".join(THAI_DIGITS[d] for d in number if d in THAI_DIGITS)


def sanitize_numbers(raw_numbers: Optional[list[str]]) -> list[str]:
    if not raw_numbers:
        return []
    cleaned: list[str] = []
    for chunk in raw_numbers:
        for piece in re.split(r"[,\s]+", chunk):
            digits = re.sub(r"[^0-9]", "", piece)
            if digits:
                cleaned.append(digits)
    return cleaned


def build_auto_prompt(numbers: list[str], bg_name: str) -> str:
    if not numbers:
        return (
            "Thai lottery poster with warm lighting, inspired by the bg_custom_เซียนตอง background, "
            "featuring vivid gold digits on a wooden board."
        )

    entries = []
    spoken = []
    for num in numbers:
        reading = digits_to_thai_words(num)
        entries.append(num)
        spoken.append(f"{num} อ่านว่า {reading}")

    numbers_clause = ", ".join(entries)
    spoken_clause = "; ".join(spoken)
    return (
        f"Thai lottery poster composition on the {bg_name} background, "
        f"displaying the numbers {numbers_clause} in large golden Thai numerals on the ticket board. "
        f"Include subtle Thai text labels denoting: {spoken_clause}. Warm studio lighting, highly detailed, 8k photograph."
    )


def select_defaults(engine: str) -> tuple[str, int, float]:
    if engine == "sdxl-turbo":
        return "stabilityai/sdxl-turbo", 4, 0.0  # turbo works with 1-4 steps, guidance ~0
    if engine == "kandinsky2.2":
        return "kandinsky-community/kandinsky-2-2-decoder", 25, 4.0
    return "runwayml/stable-diffusion-v1-5", 20, 7.5


def load_sd_pipeline(
    model_id: str,
    device: str,
    dtype: torch.dtype,
    local_files_only: bool,
) -> StableDiffusionPipeline:
    pipe = StableDiffusionPipeline.from_pretrained(
        model_id,
        torch_dtype=dtype,
        local_files_only=local_files_only,
    )
    pipe.scheduler = DPMSolverMultistepScheduler.from_config(pipe.scheduler.config)
    # Use smaller VAE if available to reduce memory footprint.
    if getattr(pipe, "vae", None) is None and "vae" in pipe.components:
        pipe.vae = AutoencoderKL.from_config(pipe.components["vae"].config)
    pipe = pipe.to(device)
    if device == "cpu":
        pipe.enable_sequential_cpu_offload()
    return pipe


def load_kandinsky_pipeline(
    device: str,
    dtype: torch.dtype,
    local_files_only: bool,
    model_id: str,
) -> tuple[KandinskyV22PriorPipeline, KandinskyV22Pipeline]:
    prior = KandinskyV22PriorPipeline.from_pretrained(
        "kandinsky-community/kandinsky-2-2-prior",
        torch_dtype=dtype,
        local_files_only=local_files_only,
    ).to(device)
    decoder = KandinskyV22Pipeline.from_pretrained(
        model_id,
        torch_dtype=dtype,
        local_files_only=local_files_only,
    ).to(device)
    return prior, decoder


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()

    device, dtype = resolve_device()
    print(f"Using device: {device} (dtype={dtype})")

    default_model, default_steps, default_guidance = select_defaults(args.engine)
    model_id = args.model or default_model
    steps = args.steps or default_steps
    guidance = args.guidance if args.guidance is not None else default_guidance

    if args.engine == "kandinsky2.2" and (args.model is None or "kandinsky" in model_id):
        prior, decoder = load_kandinsky_pipeline(device, dtype, args.local_files, model_id)
        pipe = None
    else:
        pipe = load_sd_pipeline(model_id, device, dtype, args.local_files)
        prior = decoder = None

    generator: Optional[torch.Generator] = None
    chosen_seed: int
    if args.seed is not None:
        chosen_seed = args.seed
        generator = torch.Generator(device=device).manual_seed(args.seed)
    else:
        chosen_seed = int.from_bytes(os.urandom(8), "little") & 0xFFFFFFFF
        generator = torch.Generator(device=device).manual_seed(chosen_seed)

    numbers = sanitize_numbers(args.numbers)
    if args.prompt:
        final_prompt = args.prompt
        if numbers:
            final_prompt = final_prompt + " " + build_auto_prompt(numbers, args.bg_name)
    else:
        final_prompt = build_auto_prompt(numbers, args.bg_name)

    if prior and decoder:
        prior_out = prior(
            final_prompt,
            negative_prompt=args.negative if args.negative else None,
            num_images_per_prompt=1,
            generator=generator,
        )
        image = decoder(
            image_embeds=prior_out.image_embeds,
            negative_image_embeds=prior_out.negative_image_embeds,
            height=args.height,
            width=args.width,
            generator=generator,
            num_inference_steps=steps,
            guidance_scale=guidance,
        ).images[0]
    else:
        result = pipe(
            prompt=final_prompt,
            negative_prompt=args.negative if args.negative else None,
            guidance_scale=guidance,
            num_inference_steps=steps,
            height=args.height,
            width=args.width,
            generator=generator,
        )
        image = result.images[0]

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    image.save(output_path)
    print(f"Saved image to {output_path} (seed={chosen_seed})")


if __name__ == "__main__":
    main()
